# Module template
name = "PowerRelay"
name_snake_case = "power_relay"
description = "Power relay module with optional diagnostics"
version = "1.0.0"

include.global = [ "stdint.h", "stdbool.h" ]
include.user = [ ]
is_syncronous = true
run_interval_ms = 10

[defines]
POWER_RELAY_ERROR_INTERVAL_MS = 250

[types]
PowerRelayState = { POWER_RELAY_STATE_OFF = 0, POWER_RELAY_STATE_ON = 1, POWER_RELAY_STATE_ERROR = 2 }

[interfaces]
RelayEnable.description = ""


[inputs]
[inputs.enable]
type = "bool"
init_value = "false"
description = "Relay enable request"

[inputs.diag.enable]
type = "bool"
init_value = "false"
description = "Diagnostics enable"

[inputs.diag.relay_enabled]
type = "bool"
init_value = "false"
description = "Relay enable diagnostics input"

[inputs.diag.current]
type = "uint16_t"
init_value = "0"
description = "Relay current ADC value"

[outputs]
[outputs.state]
type = "PowerRelayState"
init = "POWER_RELAY_OFF"
description = "Relay status"

